version: '3'
services:
  my.database:
    image: "postgres:11.6"
    environment:
      - "PGPORT=5432"
      - "POSTGRES_USER=user@db"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=db"
  my.service:
    build:
      context: ./
    ports:
      - "8088:8088"
    environment:
      - "DB_HOST=my.database"
    depends_on:
      - my.database
